name: Release Fruit to PYPI
desc: Release the newest version of the fruit package
glob:
  sth: empty
lists:
  dummy:
    - 1
jobs:
  release:
    desc: Compile and push the new version of fruit to PYPI
    steps:
    - step:
      name: Clean the dist/ directory
      type: system
      cmd: rm dist/*
      args: []
    - step:
      name: Run the sdist on setup.py
      type: system
      cmd: python3 setup.py sdist
      args: []
    - step:
      name: Run the wheels
      type: system
      cmd: python3 setup.py bdist_wheel sdist
      args: []
    - step:
      name: Upload with twine
      type: system
      cmd: python3 -m twine upload dist/*
      args: []